FROM node:8.10.0

# Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install yarn

# App folders
RUN mkdir -p /app/src
WORKDIR /app/src

# Node modules
COPY package.json yarn.lock ./
RUN yarn install

COPY . ./

CMD ["yarn", "run", "watch"]
