version: "3.4"

services:
  web:
    build:
      context: .
    depends_on:
      - mysql
      - redis
      - node
    ports:
      - "7000:80"
    volumes:
      - .:/app/src
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_SERVICE_HOST: redis
  mysql:
    image: "mysql:5"
    ports:
      - "33060:3306"
    volumes:
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
  redis:
    image: redis:3.2.6
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - ./resources:/app/src/resources
      - ./public:/app/src/public
      - ./package.json:/app/src/package.json
      - ./yarn.lock:/app/src/yarn.lock
